# Copyright (C) 2026 Triet Hoang <triet.hoang.dev@gmail.com>
# SPDX-License-Identifier: MIT
"""Tests for generating layer backports from the OE status cache."""

import json
import subprocess
import time
from pathlib import Path

from cve_oe_backport import backport as oe_backport


def _git(*args: str, cwd: Path) -> str:
    result = subprocess.run(
        ["git", *args], cwd=cwd, check=True, capture_output=True, text=True)
    return result.stdout.strip()


def _cached_repo(tmp_path: Path, cve: str) -> Path:
    source = tmp_path / "source"
    recipe_dir = source / "meta/recipes-connectivity/avahi"
    recipe_dir.mkdir(parents=True)
    _git("init", "-b", "scarthgap", cwd=source)
    _git("config", "user.name", "Test Author", cwd=source)
    _git("config", "user.email", "test@example.invalid", cwd=source)
    (source / "fix.txt").write_text("fixed\n")
    (recipe_dir / "avahi_0.8.bb").write_text('PN = "avahi"\nPV = "0.8"\n')
    patch_dir = recipe_dir / "files"
    patch_dir.mkdir()
    (patch_dir / f"{cve}.patch").write_text(
        "From 0123456789abcdef Mon Sep 17 00:00:00 2001\n"
        "Subject: [PATCH] Fix avahi lookup\n\n"
        f"CVE: {cve}\n"
        "Upstream-Status: Backport [https://example.invalid/fix]\n"
        "---\n avahi-core/browse.c | 1 +\n"
        "diff --git a/avahi-core/browse.c b/avahi-core/browse.c\n"
        "--- a/avahi-core/browse.c\n+++ b/avahi-core/browse.c\n"
        "@@ -1 +1,2 @@\n context\n+fixed\n")
    _git("add", ".", cwd=source)
    _git("commit", "-m", f"avahi: patch {cve} vulnerability", cwd=source)
    repos = tmp_path / "repos"
    repos.mkdir()
    cached_repo = repos / "openembedded-core"
    _git("clone", "--bare", str(source), str(cached_repo), cwd=tmp_path)
    return repos


def _cache(cve: str, status: str) -> dict:
    return {f"{cve}:scarthgap:without-token": {
        "status": status, "_ts": time.time()}}


def _metadata(cve: str, version: str = "0.8") -> dict:
    return {cve: {"name": "avahi", "version": version}}


def _set_repo_urls(monkeypatch) -> None:
    names = {
        "oe_core_url": "openembedded-core",
        "oe_core_contrib_url": "openembedded-core-contrib",
        "meta_openembedded_url": "meta-openembedded",
        "meta_openembedded_contrib_url": "meta-openembedded-contrib",
    }
    monkeypatch.setattr(
        oe_backport, "_get_repo_url",
        lambda key: f"https://example.invalid/{names[key]}")


def test_prepare_backports_writes_patch_and_bbappend(monkeypatch, tmp_path):
    cve = "CVE-2025-1234"
    repo_dir = _cached_repo(tmp_path, cve)
    layer = tmp_path / "layer"
    layer.mkdir()
    _set_repo_urls(monkeypatch)

    results = oe_backport.prepare_backports(
        _cache(cve, f'merged: "2026-02-27 4da15f7fad8d avahi: patch {cve} by Test"'),
        _metadata(cve), repo_dir, layer)

    patch = layer / "recipes-connectivity/avahi/cve-oe-backport/CVE-2025-1234.patch"
    bbappend = layer / "recipes-connectivity/avahi/avahi_0.8.bbappend"
    assert results[0]["status"] == "prepared"
    assert "CVE: CVE-2025-1234" in patch.read_text()
    assert "Upstream-Status: Backport [https://example.invalid/fix]" in patch.read_text()
    assert "diff --git a/avahi-core/browse.c" in patch.read_text()
    assert "diff --git a/meta/recipes-connectivity/avahi" not in patch.read_text()
    assert 'FILESEXTRAPATHS:prepend := "${THISDIR}/cve-oe-backport:"' in bbappend.read_text()
    assert 'SRC_URI += " file://CVE-2025-1234.patch"' in bbappend.read_text()
    assert "Generated by cve-oe-backport" in bbappend.read_text()


def test_recipe_only_commit_does_not_generate_a_patch(monkeypatch, tmp_path):
    cve = "CVE-2025-1234"
    repo_dir = _cached_repo(tmp_path, cve)
    source = tmp_path / "source"
    _git("rm", f"meta/recipes-connectivity/avahi/files/{cve}.patch", cwd=source)
    _git("commit", "--amend", "--no-edit", cwd=source)
    _git("--git-dir", str(repo_dir / "openembedded-core"), "fetch", str(source),
            "+scarthgap:scarthgap", cwd=tmp_path)
    layer = tmp_path / "layer"
    layer.mkdir()
    _set_repo_urls(monkeypatch)

    results = oe_backport.prepare_backports(
        _cache(cve, f'merged: "2026-02-27 4da15f7fad8d avahi: patch {cve} by Test"'),
        _metadata(cve), repo_dir, layer)

    assert results[0]["status"] == "error"
    assert "has no CVE patch" in results[0]["reason"]
    assert not list(layer.iterdir())


def test_prepare_backports_skips_nonmerged_status(tmp_path):
    layer = tmp_path / "layer"
    layer.mkdir()
    cve = "CVE-2025-1234"

    results = oe_backport.prepare_backports(
        _cache(cve, "not_found"), _metadata(cve), tmp_path, layer)

    assert results == []
    assert list(layer.iterdir()) == []


def test_cli_reports_when_no_merged_status(monkeypatch, tmp_path, capsys):
    repo_dir = tmp_path / "repos"
    layer = tmp_path / "layer"
    repo_dir.mkdir()
    layer.mkdir()
    (repo_dir / "oe-status-cache.json").write_text(json.dumps(_cache("CVE-2025-1234", "not_found")))
    metadata = tmp_path / "metadata.json"
    metadata.write_text(json.dumps(_metadata("CVE-2025-1234")))
    monkeypatch.setattr("sys.argv", ["cve-oe-backport", "--repo-dir", str(repo_dir),
                                    "--layer-dir", str(layer), "--cve-info", str(metadata),
                                    "--dry-run"])

    assert oe_backport.main() == 0
    assert "No merged CVE statuses matched" in capsys.readouterr().out


def test_filters_cve_and_package_before_processing(monkeypatch, tmp_path):
    cve = "CVE-2025-1234"
    other = "CVE-2025-5678"
    repo_dir = _cached_repo(tmp_path, cve)
    layer = tmp_path / "layer"
    layer.mkdir()
    _set_repo_urls(monkeypatch)
    cache = {
        **_cache(cve, f'merged: "2026-02-27 4da15f7fad8d avahi: patch {cve} by Test"'),
        **_cache(other, f'merged: "2026-02-27 4da15f7fad8d other: patch {other} by Test"'),
    }
    metadata = {**_metadata(cve), other: {"name": "other", "version": "1.0"}}

    results = oe_backport.prepare_backports(
        cache, metadata, repo_dir, layer, packages={"avahi"}, cve_ids={cve, other})

    assert [result["cve"] for result in results] == [cve]
    assert results[0]["status"] == "prepared"
    assert (layer / "recipes-connectivity/avahi/cve-oe-backport/CVE-2025-1234.patch").exists()
    assert not (layer / "recipes-connectivity/other").exists()


def test_cli_passes_repeatable_filters(monkeypatch, tmp_path):
    repo_dir = tmp_path / "repos"
    layer = tmp_path / "layer"
    repo_dir.mkdir()
    layer.mkdir()
    (repo_dir / "oe-status-cache.json").write_text("{}")
    metadata = tmp_path / "metadata.json"
    metadata.write_text("{}")
    calls = []
    monkeypatch.setattr(oe_backport, "prepare_backports", lambda *args, **kwargs: (
        calls.append(kwargs) or []))
    monkeypatch.setattr("sys.argv", ["cve-oe-backport", "--repo-dir", str(repo_dir),
                                    "--layer-dir", str(layer), "--cve-info", str(metadata),
                                    "--package", "avahi", "--package", "curl",
                                    "--cve-id", "CVE-2025-1234", "--cve-id", "CVE-2025-5678",
                                    "--dry-run"])

    assert oe_backport.main() == 0
    assert calls == [{"dry_run": True, "packages": {"avahi", "curl"},
                      "cve_ids": {"CVE-2025-1234", "CVE-2025-5678"}}]


def test_prepare_backports_does_not_overwrite_conflicting_patch(monkeypatch, tmp_path):
    cve = "CVE-2025-1234"
    repo_dir = _cached_repo(tmp_path, cve)
    layer = tmp_path / "layer"
    patch_dir = layer / "recipes-connectivity/avahi/cve-oe-backport"
    patch_dir.mkdir(parents=True)
    patch = patch_dir / "CVE-2025-1234.patch"
    patch.write_text("local change\n")
    _set_repo_urls(monkeypatch)

    results = oe_backport.prepare_backports(
        _cache(cve, f'merged: "2026-02-27 4da15f7fad8d avahi: patch {cve} by Test"'),
        _metadata(cve), repo_dir, layer)

    assert results[0]["status"] == "error"
    assert "refusing to overwrite" in results[0]["reason"]
    assert patch.read_text() == "local change\n"
    assert not (patch_dir.parent / "avahi_0.8.bbappend").exists()


def test_cache_mapping_infers_cve_and_branch():
    cve = "CVE-2025-1234"
    cache = _cache(
        cve, f'merged: "2026-02-27 4da15f7fad8d avahi: patch {cve} by Test"')

    mapping, unresolved = oe_backport._cache_mapping(cache)

    assert mapping[f"{cve}:scarthgap"] == {"cve": cve, "branch": "scarthgap"}
    assert unresolved == []


def test_expired_merged_cache_still_prepares_patch(monkeypatch, tmp_path):
    cve = "CVE-2025-1234"
    repo_dir = _cached_repo(tmp_path, cve)
    layer = tmp_path / "layer"
    layer.mkdir()
    _set_repo_urls(monkeypatch)
    cache = _cache(cve, f'merged: "2026-02-27 4da15f7fad8d avahi: patch {cve} by Test"')
    cache[f"{cve}:scarthgap:without-token"]["_ts"] = time.time() - 86400

    results = oe_backport.prepare_backports(cache, _metadata(cve), repo_dir, layer)

    assert results[0]["status"] == "prepared"
    assert (layer / "recipes-connectivity/avahi/cve-oe-backport/CVE-2025-1234.patch").exists()


def test_version_mismatch_warns_but_prepares_patch(monkeypatch, tmp_path):
    cve = "CVE-2025-1234"
    repo_dir = _cached_repo(tmp_path, cve)
    layer = tmp_path / "layer"
    layer.mkdir()
    _set_repo_urls(monkeypatch)

    results = oe_backport.prepare_backports(
        _cache(cve, f'merged: "2026-02-27 4da15f7fad8d avahi: patch {cve} by Test"'),
        _metadata(cve, "0.7"), repo_dir, layer)

    assert results[0]["status"] == "prepared"
    assert "metadata version 0.7 differs" in results[0]["warning"]
    assert (layer / "recipes-connectivity/avahi/cve-oe-backport/CVE-2025-1234.patch").exists()
    assert (layer / "recipes-connectivity/avahi/avahi_0.7.bbappend").exists()


def test_existing_bbappend_is_preserved_and_extended(monkeypatch, tmp_path):
    cve = "CVE-2025-1234"
    repo_dir = _cached_repo(tmp_path, cve)
    layer = tmp_path / "layer"
    append = layer / "recipes-connectivity/avahi/avahi_0.8.bbappend"
    append.parent.mkdir(parents=True)
    append.write_text('SUMMARY = "Existing append"\n')
    _set_repo_urls(monkeypatch)

    results = oe_backport.prepare_backports(
        _cache(cve, f'merged: "2026-02-27 4da15f7fad8d avahi: patch {cve} by Test"'),
        _metadata(cve), repo_dir, layer)

    content = append.read_text()
    assert results[0]["status"] == "prepared"
    assert content.startswith('SUMMARY = "Existing append"\n')
    assert "Generated by cve-oe-backport" in content
    assert 'file://CVE-2025-1234.patch' in content
